# 应用相关
APP:
  APP_NAME: "METAPHYSICS"
  APP_HOST: "127.0.0.1" # 如果使用 docker，则改为"0.0.0.0"
  APP_PORT: "8080"
  # 邮箱相关
  EMAIL:
    EMAIL_TYPE: "qq" # 支持的邮箱类型: qq, gmail, outlook
    FROM_EMAIL: "<FROM_EMAIL>" # 发件人邮箱
    EMAIL_SMTP: "<EMAIL_SMTP>" # SMTP 授权码

# 数据库相关
DATABASE:
  DB_DIALECT: "postgres" # 数据库类型, 可选值: postgres, mysql, sqlite
  DB_NAME: "metaphysics_db"
  DB_HOST: "127.0.0.1" # 如果使用 docker，则改为"postgres_db"
  DB_PORT: "5432"
  DB_USER: "root"
  DB_PSW: "123456"
  DB_PATH: "./database" # SQLite 数据库文件路径

# Redis 相关
REDIS:
  REDIS_HOST: "127.0.0.1" # 如果使用 docker，则改为"redis_db"
  REDIS_PORT: "6379"
  REDIS_PSW: ""
  REDIS_DB: "0"

# 日志相关
LOG:
  LOG_FILE_PATH: ".logs/"
  LOG_FILE_NAME: "app.log"
  LOG_TIMESTAMP_FMT: "2006-01-02 15:04:05"
  LOG_MAX_AGE: 72
  LOG_ROTATION_TIME: 24
  LOG_LEVEL: "INFO"

# AI 相关
AI:
  # ollama配置
  OLLAMA_ENABLED: true # 是否启用 ollama
  OLLAMA_API_BASE: "http://localhost:11434" # ollama API 基础 URL
  OLLAMA_MODEL: "qwen3:8b" # ollama 模型名称
  # deepseek配置
  DEEPSEEK_ENABLED: false # 是否启用 deepseek
  DEEPSEEK_API_KEY: "your-deepseek-api-key" # 请替换为您的 deepseek API 密钥
  DEEPSEEK_API_BASE: "https://api.deepseek.com" # deepseek API 基础 URL
  DEEPSEEK_MODEL: "deepseek-reasoner" # deepseek 模型名称
